/**
 * Monitor `host_data.event` names: definitions align with HPCPerfStats/monitor schema KEYS.
 * Regenerate: python3 hpcperfstats/site/frontend/src/utils/generate-variable-metadata-monitor-events.py
 * (see HPCPerfStats/hpcperfstats/cursor-rules/variable-metadata-monitor-contract.mdc).
 */

export const MONITOR_EVENT_METADATA = {
  MBW_CHANNEL_0: { description: "Historical AMD DF DRAM channel bandwidth counter (legacy archives; dual-read with dram_chan0_bytes)." },
  MBW_CHANNEL_1: { description: "Historical AMD DF DRAM channel bandwidth counter (legacy archives; dual-read with dram_chan1_bytes)." },
  MBW_CHANNEL_2: { description: "Historical AMD DF DRAM channel bandwidth counter (legacy archives; dual-read with dram_chan2_bytes)." },
  MBW_CHANNEL_3: { description: "Historical AMD DF DRAM channel bandwidth counter (legacy archives; dual-read with dram_chan3_bytes)." },
  MBW_CHANNEL_4: { description: "Historical AMD DF DRAM channel bandwidth counter for one DF DRAM channel (legacy 8-channel archives)." },
  MBW_CHANNEL_5: { description: "Historical AMD DF DRAM channel bandwidth counter for one DF DRAM channel (legacy 8-channel archives)." },
  MBW_CHANNEL_6: { description: "Historical AMD DF DRAM channel bandwidth counter for one DF DRAM channel (legacy 8-channel archives)." },
  MBW_CHANNEL_7: { description: "Historical AMD DF DRAM channel bandwidth counter for one DF DRAM channel (legacy 8-channel archives)." },
  READ_ops: { description: "NFS READ RPC operation count (mountstats)." },
  READ_queue: { description: "NFS READ time queued before transmission (milliseconds)." },
  READ_rtt: { description: "NFS READ round-trip time (milliseconds)." },
  READ_timeouts: { description: "NFS READ major timeouts." },
  SIMD_DOUBLE_256: { description: "Intel core PMU: retired 256-bit packed double-precision SIMD FP operations (legacy FLOP proxy)." },
  SSE_DOUBLE_PACKED: { description: "Intel core PMU: retired SSE/AVX packed double-precision FP operations (legacy FLOP proxy)." },
  SSE_DOUBLE_SCALAR: { description: "Intel core PMU: retired SSE/AVX double-precision scalar FP operations (legacy FLOP proxy)." },
  WRITE_ops: { description: "NFS WRITE RPC operation count." },
  WRITE_queue: { description: "NFS WRITE time queued before transmission (milliseconds)." },
  WRITE_rtt: { description: "NFS WRITE round-trip time (milliseconds)." },
  WRITE_timeouts: { description: "NFS WRITE major timeouts." },
  active: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  allocstall: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  anon_huge_pages: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  anon_pages: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  aperf: { description: "Active cycles (util-scaled). Grace DCGM fail-soft: act = mperf * (util_total / 100); on x86, MSR/FIXED actual/unhalted cycle counters rename to this key." },
  arm_dram_bw_bytes: { description: "Synthetic cumulative DRAM byte traffic estimate for ARM/DCGM-backed paths (monitor-derived)." },
  arm_est_flops: { description: "Grace host_cpu_hw: estimated floating-point operations per interval as SP+DP scalar only (does not include arm_int8_ops / arm_int16_ops)." },
  arm_int16_ops: { description: "Grace host_cpu_hw: INT16 arithmetic operations from ASE_SVE_INT16_SPEC (PAPI fail-soft may report zero)." },
  arm_int8_ops: { description: "Grace host_cpu_hw: INT8 arithmetic operations from ASE_SVE_INT8_SPEC (PAPI fail-soft may report zero)." },
  bounce: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  bypass_cha_imc_all: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  bytes_avail: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  bytes_used: { description: "Tmpfs: bytes used on the tmpfs mount." },
  clocks_event_reasons: { description: "GPU clock throttle reasons bitmask (DCGM on `nvidia_gpu`; same KEY on `amd_gpu` when populated)." },
  collisions: { description: "Ethernet collision counter (half-duplex legacy)." },
  counter_select: { description: "IB MAD extended counter query selector field." },
  cpu_clock_est_cycles: { description: "Active cycles (same as aperf under Grace DCGM fail-soft util-scaled estimate). PAPI may overwrite when measured cycles are nonzero." },
  cpu_peak_dram_bw_bytes_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_peak_fp64_flops_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_peak_hbm_bw_bytes_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_peak_source: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_util_irq_accum_us: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_util_nice_accum_us: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_util_sys_accum_us: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_util_total_accum_us: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cpu_util_user_accum_us: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  ctxt: { description: "Context switches (global, from /proc/stat via ps stats type)." },
  cycles_unhalted_core: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  cycles_unhalted_ref: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dcgm_cpu_power_limit_w: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dcgm_cpu_power_util_w: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dentry_use: { description: "VFS: directory cache entries in use (approximate from dentry-state)." },
  direct_read: { description: "NFS direct I/O read bytes." },
  direct_write: { description: "NFS direct I/O write bytes." },
  dirty: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dram_act_count: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dram_cas_reads: { description: "Memory-controller DRAM CAS read events (Intel uncore IMC or normalized ARM IMC), used for DRAM bandwidth." },
  dram_cas_writes: { description: "Memory-controller DRAM CAS write events." },
  dram_chan0_bytes: { description: "AMD DF DRAM channel 0 byte counter from amd_x86_uncore_df_{rome,milan,genoa,turin} (LIKWID)." },
  dram_chan1_bytes: { description: "AMD DF DRAM channel 1 byte counter from amd_x86_uncore_df_{rome,milan,genoa,turin} (LIKWID)." },
  dram_chan2_bytes: { description: "AMD DF DRAM channel 2 byte counter from amd_x86_uncore_df_{rome,milan,genoa,turin} (LIKWID)." },
  dram_chan3_bytes: { description: "AMD DF DRAM channel 3 byte counter from amd_x86_uncore_df_{rome,milan,genoa,turin} (LIKWID)." },
  dram_energy: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  dram_pre_count_miss: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  errors: { description: "LNET error counter." },
  excessive_buffer_overrun_errors: { description: "InfiniBand port counter: excessive buffer overruns (base IB sysfs counters)." },
  file_pages: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  file_use: { description: "VFS: open file handles in use (/proc/sys/fs/file-nr)." },
  files_used: { description: "Tmpfs: number of files in use on the mount." },
  fp16_active: { description: "FP16 pipe activity percent (DCGM PROF on NVIDIA; shared KEY on `amd_gpu`)." },
  fp32_active: { description: "FP32 pipe activity percent (DCGM PROF on NVIDIA; shared KEY on `amd_gpu`)." },
  fp64_active: { description: "FP64 pipe activity ratio as percent. DCGM PROF on `nvidia_gpu`; same semantic field on `amd_gpu` (wave/SM naming differs)." },
  fp_arith_inst_retired_128b_packed_double: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_128b_packed_single: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_256b_packed_double: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_256b_packed_single: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_512b_packed_double: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_512b_packed_single: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  fp_arith_inst_retired_scalar_double: { description: "Grace host_cpu_hw: retired scalar double-precision FP arithmetic instructions." },
  fp_arith_inst_retired_scalar_single: { description: "Grace host_cpu_hw: retired scalar single-precision FP arithmetic instructions." },
  fs_bytes_avail: { description: "Lustre llite mount capacity: available bytes for unprivileged users from sysfs (gauge)." },
  fs_bytes_free: { description: "Lustre llite mount capacity: free bytes from sysfs (gauge)." },
  fs_bytes_total: { description: "Lustre llite mount capacity: total bytes from sysfs (gauge; not a rate)." },
  fs_files_free: { description: "Lustre llite mount capacity: free inode count from sysfs (gauge)." },
  fs_files_total: { description: "Lustre llite mount capacity: total inode count from sysfs (gauge)." },
  gpu_count: { description: "GPU device count for the monitor row. DCGM-visible GPU count on `nvidia_gpu`; `amd_gpu` schema documents a stub row count (often 1)." },
  gpu_dram_active: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_flops: { description: "Cumulative estimated GPU FLOPs (monitor-integrated model; both GPU types)." },
  gpu_flops_rate: { description: "Instantaneous estimated GPU FLOP/s (monitor model; both GPU types expose this KEY)." },
  gpu_io_link_total_bytes: { description: "NVIDIA-only (`nvidia_gpu` / DCGM): cumulative PCIe plus NVLink bytes from DCGM PROF link counters (not HBM/VRAM traffic). This KEY is not in `amd_gpu.h`; the AMD monitor schema stops at `gpu_mem_total_bytes` plus `gpu_count`." },
  gpu_mem_bw_bytes_rate: { description: "Estimated GPU memory bandwidth (bytes/s) from the monitor model. DCGM-backed on `nvidia_gpu`; `amd_gpu` uses the same schema key." },
  gpu_mem_free_mb: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_mem_read_bytes: { description: "Cumulative estimated GPU memory read bytes (model; shared `amd_gpu` / `nvidia_gpu` schema)." },
  gpu_mem_total_bytes: { description: "Cumulative estimated GPU memory traffic bytes (model; shared schema)." },
  gpu_mem_total_mb: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_mem_used_mb: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_mem_util: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_mem_write_bytes: { description: "Cumulative estimated GPU memory write bytes (model; shared schema)." },
  gpu_nvlink_rx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_nvlink_tx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_pcie_replay_counter: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_pcie_rx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_pcie_tx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_peak_fp64_flops_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_peak_io_link_bw_bytes_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_peak_mem_bw_bytes_per_s: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_peak_source: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_sm_clock: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_util: { description: "GPU utilization percent. Populated from DCGM on `nvidia_gpu`; from GPUPerfAPI (or stub zeros) on `amd_gpu`." },
  gpu_xe_link_rx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  gpu_xe_link_tx_bytes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  hbm_cas_reads: { description: "SPR IMC HBM CAS read count (intel_x86_uncore_imc_spr); paired with hbm_cas_writes for measured HBM BW." },
  hbm_cas_writes: { description: "SPR IMC HBM CAS write count (intel_x86_uncore_imc_spr); paired with hbm_cas_reads for measured HBM BW." },
  huge_pages_free: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  huge_pages_total: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  idle: { description: "Cumulative CPU idle time." },
  in_flight: { description: "Number of I/O requests currently in flight to the device." },
  inactive: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  inode_use: { description: "VFS: inodes in use (inode-state)." },
  instr_retired: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  instr_retired_any: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  interleave_hit: { description: "NUMA interleave policy hits." },
  io_ticks: { description: "Time the disk queue was actively servicing I/O (milliseconds)." },
  iowait: { description: "Cumulative CPU time waiting for block I/O." },
  irq: { description: "Cumulative CPU time handling hardware interrupts." },
  kswapd_inodesteal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  kswapd_steal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  l1d_replacement: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  ldlm_cancel: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  link_downed: { description: "InfiniBand port counter: failed link error recoveries (link went down; monitor comment in ib.c)." },
  link_error_recovery: { description: "InfiniBand port counter: successful link error recovery events (monitor ib.c)." },
  llc_lookup_data_read_local: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  llc_lookup_write: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  load_1: { description: "One-minute load average (monitor often scales by 100; see unit metadata)." },
  load_15: { description: "Fifteen-minute load average." },
  load_5: { description: "Five-minute load average." },
  local_link_integrity_errors: { description: "InfiniBand port counter: local link integrity errors (hardware / cable quality)." },
  local_node: { description: "Local-node memory accesses (numastat)." },
  ls_dispatch: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mapped: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mds_close: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_getattr: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_getattr_lock: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_getxattr: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_readpage: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_statfs: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mds_sync: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  mem_free: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mem_load_uops_retired_l1_hit: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mem_load_uops_retired_l2_hit: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mem_load_uops_retired_llc_hit: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mem_total: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  mem_used: { description: "System V shared memory: total bytes used across segments." },
  module_power_usage: { description: "NVIDIA-only (`nvidia_gpu` / DCGM): module-scope power (watts) on integrated packages. Omitted from `amd_gpu` KEYS." },
  mperf: { description: "Reference cycles (wall/TSC-like). Grace DCGM fail-soft: ref = clock_khz * delta_t_us / 1000; on x86, MSR/FIXED reference cycle counters rename to this key." },
  msgs_alloc: { description: "Lustre LNET: messages currently allocated." },
  msgs_alloc_max: { description: "LNET high-water mark of allocated messages." },
  multicast: { description: "Multicast packet counter (receive path; naming varies by driver)." },
  nfs_unstable: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  nice: { description: "Cumulative CPU time in low-priority user mode." },
  normal_read: { description: "NFS normal read bytes." },
  normal_write: { description: "NFS normal write bytes." },
  nr_anon_transparent_hugepages: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  nr_running: { description: "Runnable tasks on the run queue (ps/global stat)." },
  nr_threads: { description: "Thread count from global /proc/stat-derived ps sample." },
  numa_foreign: { description: "Pages counted as foreign to the allocating node." },
  numa_hit: { description: "NUMA allocations satisfied on the preferred node (/sys/.../numastat)." },
  numa_miss: { description: "NUMA allocations that missed the preferred node (numastat)." },
  ost_destroy: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  ost_punch: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  ost_read: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  ost_setattr: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  ost_statfs: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  ost_write: { description: "Lustre client metadata (MDC) or OSC statistic from /proc/fs/lustre." },
  other_node: { description: "Remote-node memory accesses (numastat)." },
  page_tables: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  pageoutrun: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  peak_calc_version: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  pgactivate: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgalloc_normal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgdeactivate: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgfault: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgfree: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pginodesteal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgmajfault: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgpgin: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgpgout: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgrefill_normal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgrotated: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgscan_direct_normal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgscan_kswapd_normal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pgsteal_normal: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pkg_energy: { description: "CPU package energy (mJ) from intel_x86_rapl or amd_x86_rapl; drives summary watts / amd_pkg_w and node power estimates." },
  port_error_counter_summary: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_mark_fecn: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_multicast_rcv_pkts: { description: "Multicast packets received (IB extended)." },
  port_multicast_xmit_pkts: { description: "Multicast packets transmitted (IB extended)." },
  port_rcv_becn: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_bubble: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_constraint_errors: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_data: { description: "InfiniBand counter: payload bytes received." },
  port_rcv_errors: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_fecn: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_packets: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_rcv_pkts: { description: "Packets received (IB counters)." },
  port_rcv_remote_physical_errors: { description: "InfiniBand inbound physical-layer error counter." },
  port_rcv_switch_relay_errors: { description: "InfiniBand switch relay errors on received traffic." },
  port_select: { description: "IB MAD extended counter query selector field (configuration metadata)." },
  port_unicast_rcv_pkts: { description: "Unicast packets received (IB extended)." },
  port_unicast_xmit_pkts: { description: "Unicast packets transmitted (IB extended)." },
  port_xmit_constraint_errors: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_xmit_data: { description: "InfiniBand counter: payload bytes transmitted (width/units per IBTA and sysfs docs)." },
  port_xmit_discards: { description: "Packets not transmitted because the port was down or congested." },
  port_xmit_packets: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_xmit_pkts: { description: "Packets transmitted (IB counters)." },
  port_xmit_time_cong: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_xmit_wait: { description: "Time waiting for credits or arbitration (vendor-specific units)." },
  port_xmit_wait_data: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  port_xmit_wasted_bw: { description: "Network or fabric port performance counter (InfiniBand sysfs, extended MAD, or Omni-Path)." },
  power_usage: { description: "GPU power draw (watts). DCGM on `nvidia_gpu`; device-reported path on `amd_gpu` when available." },
  pp0_energy: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  pp1_energy: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  processes: { description: "Processes created (forks) from /proc/stat." },
  pswpin: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  pswpout: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  rd_ios: { description: "Completed read I/O operations." },
  rd_merges: { description: "Read requests merged with the in-queue I/O queue." },
  rd_sectors: { description: "Sectors read from the block device (512-byte sectors, Linux sysfs block stat)." },
  rd_ticks: { description: "Time spent on read I/O (milliseconds)." },
  read_bytes: { description: "Cumulative bytes read on the Lustre client from llite or OSC `/proc/fs/lustre/*/stats` (legacy name; canonical emit is `vfs_read_bytes`)." },
  reqs: { description: "Lustre OSC: sample count taken from `req_waittime` lines in `/proc/fs/lustre/osc/*/stats` (paired with `wait`)." },
  retired_branch_instr: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  retired_instructions: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  retired_misp_branch_instr: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  route_bytes: { description: "LNET routed bytes." },
  route_msgs: { description: "LNET routed messages (routers)." },
  rx_bytes: { description: "Bytes received (Ethernet per-interface sysfs, or another type—disambiguate with host_data.type)." },
  rx_bytes_dropped: { description: "LNET receive bytes dropped." },
  rx_compressed: { description: "Linux netdev: received compressed frames (per-interface sysfs statistics)." },
  rx_crc_errors: { description: "Linux netdev: frames received with CRC or FCS errors (physical layer or interference)." },
  rx_dropped: { description: "Receive drops (kernel or driver)." },
  rx_errors: { description: "Receive errors reported by the driver." },
  rx_fifo_errors: { description: "Linux netdev: receiver FIFO overrun errors." },
  rx_frame_errors: { description: "Linux netdev: framing errors (misaligned or malformed Ethernet frames)." },
  rx_length_errors: { description: "Linux netdev: received frames with invalid length field." },
  rx_missed_errors: { description: "Linux netdev: packets missed by the receiver (often ring buffer exhaustion)." },
  rx_msgs: { description: "LNET messages received." },
  rx_msgs_dropped: { description: "LNET receive messages dropped." },
  rx_over_errors: { description: "Linux netdev: receiver overrun errors." },
  rx_packets: { description: "Packets received (per-interface sysfs)." },
  segs_used: { description: "System V shared memory: number of segments in use." },
  server_read: { description: "NFS server-side read bytes (mountstats accounting)." },
  server_write: { description: "NFS server-side write bytes." },
  sf_evictions_mes: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  slab: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  slabs_scanned: { description: "Kernel VM statistic from /proc/vmstat (Linux kernel documentation)." },
  sm_active: { description: "SM (or CU) activity percent: DCGM PROF on `nvidia_gpu`; GPUPerfAPI-style on `amd_gpu`." },
  sm_occupancy: { description: "Occupancy percent: DCGM warp occupancy on NVIDIA; AMD uses active-wave occupancy wording in schema." },
  softirq: { description: "Cumulative CPU time in softirq bottom halves." },
  sw_port_congestion: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  sw_rx_bytes: { description: "IB switch-port received payload bytes (MAD extended 64-bit counters)." },
  sw_rx_packets: { description: "IB switch-port received packets." },
  sw_tx_bytes: { description: "IB switch-port transmitted payload bytes." },
  sw_tx_packets: { description: "IB switch-port transmitted packets." },
  symbol_error: { description: "Minor link symbol errors on InfiniBand." },
  sysio_power_usage: { description: "NVIDIA-only (`nvidia_gpu` / DCGM): SysIO instantaneous power (watts). Not present in the slimmer `amd_gpu` monitor schema." },
  system: { description: "Cumulative CPU time in kernel mode." },
  temperature: { description: "GPU temperature (degrees C). DCGM on `nvidia_gpu`; `amd_gpu` when GPUPerfAPI supplies it." },
  tensor_active: { description: "GPU tensor/matrix pipe activity as percent in monitor output. On `nvidia_gpu` this comes from DCGM PROF; `amd_gpu` shares the same KEY name with a slimmer schema." },
  tensor_dfma_active: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  tensor_hmma_active: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  tensor_imma_active: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  thp_collapse_alloc: { description: "Linux /proc/vmstat: successful collapse of page tables into a THP." },
  thp_collapse_alloc_failed: { description: "Linux /proc/vmstat: failed attempts to collapse mappings into a THP." },
  thp_fault_alloc: { description: "Linux /proc/vmstat: transparent hugepage allocations satisfied on fault." },
  thp_fault_fallback: { description: "Linux /proc/vmstat: THP fault handling fell back to small pages." },
  thp_split: { description: "Linux /proc/vmstat: transparent hugepage splits (e.g. unmap, compaction, or policy)." },
  threads: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  time_in_queue: { description: "Accumulated time requests spent in the I/O scheduler queue (milliseconds)." },
  tx_aborted_errors: { description: "Linux netdev: aborted transmissions (driver or hardware abort)." },
  tx_bytes: { description: "Bytes transmitted (Ethernet per-interface sysfs, Lustre LNET, or other type—use host_data.type)." },
  tx_carrier_errors: { description: "Linux netdev: loss of carrier during transmit (cable, duplex, or link partner)." },
  tx_compressed: { description: "Linux netdev: transmitted compressed frames." },
  tx_dropped: { description: "Transmit drops." },
  tx_errors: { description: "Transmit errors reported by the driver." },
  tx_fifo_errors: { description: "Linux netdev: transmit FIFO errors (underrun/overrun, driver dependent)." },
  tx_heartbeat_errors: { description: "Linux netdev: heartbeat / half-duplex loss-of-carrier style errors." },
  tx_msgs: { description: "LNET messages transmitted." },
  tx_packets: { description: "Packets transmitted." },
  tx_window_errors: { description: "Linux netdev: classic transmitter window errors on outbound frames." },
  uid: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  user: { description: "Cumulative CPU time in user mode (per-core counter; units per Linux /proc/stat, typically jiffies)." },
  vfs_alloc_inode_ops: { description: "Lustre llite: inode allocation operations (canonical vfs_* KEY)." },
  vfs_close_ops: { description: "Lustre llite: `close(2)` operation count (canonical vfs_* KEY)." },
  vfs_create_ops: { description: "Lustre llite: file create operation count (canonical vfs_* KEY)." },
  vfs_direct_read_bytes: { description: "Lustre llite: cumulative direct-I/O read bytes on this mount." },
  vfs_direct_write_bytes: { description: "Lustre llite: cumulative direct-I/O write bytes on this mount." },
  vfs_dirty_page_hits: { description: "Lustre llite: dirty client-page cache hits." },
  vfs_dirty_page_misses: { description: "Lustre llite: dirty client-page cache misses." },
  vfs_flock_ops: { description: "Lustre llite: advisory `flock` operation count (canonical vfs_* KEY)." },
  vfs_fsync_ops: { description: "Lustre llite: `fsync` operation count (canonical vfs_* KEY)." },
  vfs_getattr_ops: { description: "Lustre llite: getattr / stat-style metadata operation count (canonical vfs_* KEY)." },
  vfs_getxattr_ops: { description: "Lustre llite: `getxattr` syscall count (canonical vfs_* KEY)." },
  vfs_inode_permission_ops: { description: "Lustre llite: inode permission check count (canonical vfs_* KEY)." },
  vfs_ioctl_ops: { description: "Lustre llite: `ioctl` operation count on this mount." },
  vfs_link_ops: { description: "Lustre llite: hard `link` operation count (canonical vfs_* KEY)." },
  vfs_listxattr_ops: { description: "Lustre llite: `listxattr` syscall count (canonical vfs_* KEY)." },
  vfs_lookup_ops: { description: "Lustre llite: pathname `lookup` operation count (canonical vfs_* KEY)." },
  vfs_mkdir_ops: { description: "Lustre llite: `mkdir` operation count (canonical vfs_* KEY)." },
  vfs_mknod_ops: { description: "Lustre llite: `mknod` operation count (canonical vfs_* KEY)." },
  vfs_mmap_ops: { description: "Lustre llite: `mmap` operation count (canonical vfs_* KEY)." },
  vfs_open_ops: { description: "Lustre llite: `open(2)` operation count (canonical vfs_* KEY)." },
  vfs_osc_read_bytes: { description: "Lustre llite: bytes attributed to the OSC read path in llite stats." },
  vfs_osc_write_bytes: { description: "Lustre llite: bytes attributed to the OSC write path in llite stats." },
  vfs_read_bytes: { description: "Lustre llite: cumulative bytes read on this client mount (canonical vfs_* KEY from `/proc/fs/lustre/llite/*/stats`)." },
  vfs_read_ops: { description: "Lustre llite: `read(2)` operation count (canonical vfs_* KEY; volume in `vfs_read_bytes`)." },
  vfs_readdir_ops: { description: "Lustre llite: `readdir` operation count (canonical vfs_* KEY)." },
  vfs_removexattr_ops: { description: "Lustre llite: `removexattr` syscall count (canonical vfs_* KEY)." },
  vfs_rename_ops: { description: "Lustre llite: `rename` operation count (canonical vfs_* KEY)." },
  vfs_rmdir_ops: { description: "Lustre llite: `rmdir` operation count (canonical vfs_* KEY)." },
  vfs_seek_ops: { description: "Lustre llite: `seek` operation count (canonical vfs_* KEY)." },
  vfs_setattr_ops: { description: "Lustre llite: `setattr` metadata updates (canonical vfs_* KEY)." },
  vfs_setxattr_ops: { description: "Lustre llite: `setxattr` syscall count (canonical vfs_* KEY)." },
  vfs_statfs_ops: { description: "Lustre llite: `statfs` operation count (canonical vfs_* KEY)." },
  vfs_symlink_ops: { description: "Lustre llite: `symlink` creation operation count (canonical vfs_* KEY)." },
  vfs_truncate_ops: { description: "Lustre llite: `truncate` operation count (canonical vfs_* KEY)." },
  vfs_unlink_ops: { description: "Lustre llite: `unlink` operation count (canonical vfs_* KEY)." },
  vfs_write_bytes: { description: "Lustre llite: cumulative bytes written on this client mount (canonical vfs_* KEY)." },
  vfs_write_ops: { description: "Lustre llite: `write(2)` operation count (canonical vfs_* KEY; volume in `vfs_write_bytes`)." },
  vl15_dropped: { description: "Retired InfiniBand VL 15 dropped-frame counter (historical host_data only; no longer emitted by the monitor)." },
  vm_data: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_exe: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_hwm: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_lck: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_lib: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_peak: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_pte: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_rss: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_size: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_stk: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  vm_swap: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  wait: { description: "Lustre OSC: cumulative microseconds from the `req_waittime` sum field in `/proc/fs/lustre/osc/*/stats` (use deltas with `reqs` for average wait in a window)." },
  wr_ios: { description: "Completed write I/O operations." },
  wr_merges: { description: "Write requests merged with the in-queue I/O queue." },
  wr_sectors: { description: "Sectors written to the block device (512-byte sectors)." },
  wr_ticks: { description: "Time spent on write I/O (milliseconds)." },
  write_bytes: { description: "Cumulative bytes written on the Lustre client from llite or OSC `/proc/fs/lustre/*/stats` (legacy name; canonical emit is `vfs_write_bytes`)." },
  writeback: { description: "Telemetry field published by the HPCPerfStats monitor as host_data.event (see monitor/src for the owning stats type)." },
  xprt_bad_xids: { description: "NFS RPC transport bad XID count." },
  xprt_bklog_u: { description: "NFS transport backlog utilization accumulator." },
  xprt_req_u: { description: "NFS transport accumulated in-flight request measure (kernel xprt stats)." },
};
