services:
  web:
    build: ./
    image: hpcperfstats
    links:
      - db
    command: /home/hpcperfstats/services-conf/django_startup.sh
    env_file:
      - ./.env.dev
    volumes:
      - hpcperfstatsweblog:/hpcperfstats/logs/

  pipeline:
    image: hpcperfstats
    links:
      - db
      - rabbitmq
    depends_on:
      - web
    command: /home/hpcperfstats/services-conf/supervisor_startup.sh
    volumes:
      - hpcperfstatsdata:/hpcperfstats/
      - /home/sharrell/.ssh:/hpcperfstats/.ssh/
    env_file:
      - ./.env.dev

  proxy:
    restart: always
    image: nginx:1-alpine
    links:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services-conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/

  db:
    image: timescale/timescaledb:latest-pg15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hpcperfstats
      - POSTGRES_PASSWORD=hpcperfstats

  rabbitmq:
    image: rabbitmq:4-alpine
    ports:
        - 5672:5672
    # Admin Console
    #    - 15672:15672
    volumes:
        - rabbitmq_messages:/var/lib/rabbitmq/
        - /var/log/rabbitmq:/var/log/rabbitmq

volumes:
      postgres_data:

      rabbitmq_messages:
      
      hpcperfstatsdata:
        driver: local
        driver_opts:
          type: none
          device: /home/sharrell/s3-stats/hpcperfstats_data/
          o: bind
      
      hpcperfstatsweblog:
        driver: local
        driver_opts:
          type: none
          device: /home/sharrell/s3-stats/hpcperfstats_log
          o: bind
