# Generated by Django 3.1.14 on 2025-06-25 16:07

from django.db import migrations
import hpcperfstats.conf_parser as cfg

dbname = cfg.get_db_name()


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE USER statsro WITH PASSWORD 'statsro';"
        ),

        migrations.RunSQL(
            "GRANT CONNECT ON DATABASE %s TO statsro;" % dbname
        ),

        migrations.RunSQL(
            "GRANT USAGE ON SCHEMA public TO statsro;"
        ),

        migrations.RunSQL(
            "GRANT SELECT ON ALL TABLES IN SCHEMA public TO statsro;"
        ),

        migrations.RunSQL(
            "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO statsro;"
        ),
    ]
