# Generated by Django 5.2.12 on 2026-03-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_add_read_only_user'),
    ]

    operations = [
              migrations.RunSQL("CREATE INDEX idx_host ON host_data (host)"),
    ]
    
