# Generated by Django 6.0.3 on 2026-03-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_apikey_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='job_data',
            name='end_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='metrics_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metrics_data',
            name='jid',
            field=models.ForeignKey(blank=True, db_column='jid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics_data_set', to='machine.job_data'),
        ),
        migrations.AlterField(
            model_name='proc_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proc_data',
            name='jid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['username'], name='api_keys_username_idx'),
        ),
    ]
