# Django settings for hpcperfstats_site project. Database, auth, templates, static, and app config from conf_parser and env.
#
import os
import sys
import warnings

import hpcperfstats.conf_parser as cfg
from django.core.cache.backends.base import CacheKeyWarning

DIR = os.path.dirname(os.path.abspath(__file__))

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Number of threads for OpenBLAS. Used by wsgi.py as the default value for
# OPENBLAS_NUM_THREADS when the environment variable is not already set.
OPENBLAS_NUM_THREADS = 4

# SECRET_KEY: env overrides ini; required in production (set in env or hpcperfstats.ini [DEFAULT] secret_key).
SECRET_KEY = os.environ.get("SECRET_KEY") or cfg.get_secret_key()
DEBUG = cfg.get_debug()

# Skip Redis caching for job plot json_items when UTF-8 JSON exceeds this size (default 512 KiB).
JOB_PLOT_REDIS_MAX_BYTES = int(os.environ.get("JOB_PLOT_REDIS_MAX_BYTES", "524288"))

# Django 6+: ADMINS/MANAGERS are list of email strings (name in tuple deprecated).
ADMINS = ["sharrell@tacc.utexas.edu"]
MANAGERS = ["sharrell@tacc.utexas.edu"]

# Set cookies properly: HttpOnly and Secure in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

# SecurityMiddleware configuration.
#
# nginx is responsible for TLS termination, so teach Django to trust
# X-Forwarded-Proto to decide when a request is secure (e.g. for HSTS).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HSTS matches the previous nginx policy (max-age + includeSubDomains),
# but is now generated by Django so responses are consistent behind gunicorn
# (direct) and behind nginx (proxy).
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = False

# Keep UI framing policy aligned with prior nginx behavior.
X_FRAME_OPTIONS = "SAMEORIGIN"

# Reduce MIME-sniffing risk.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Avoid leaking full referrer URLs.
SECURE_REFERRER_POLICY = "same-origin"

# CSRF cookies are set by Django; ensure they are also marked Secure when
# running in production-style deployments behind TLS-terminating nginx.
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"

# Give a name that is unique for the computing platform
# CONN_MAX_AGE: persistent connections per worker/thread (see conf_parser.get_db_conn_max_age).
# Default 90s returns idle backends sooner under load; override via DJANGO_CONN_MAX_AGE or ini.
# CONN_HEALTH_CHECKS: verify connection before reuse (Django 4.1+).
# PostgreSQL OPTIONS: statement_timeout and idle_in_transaction_session_timeout (see conf_parser).
_db_conn_max_age = cfg.get_db_conn_max_age()
_default_engine = cfg.get_engine_name()
_default_db = {
    'ENGINE': _default_engine,
    'NAME': '{0}'.format(cfg.get_db_name()),
    'USER': cfg.get_username(),
    'PASSWORD': cfg.get_password(),
    'HOST': cfg.get_host(),
    'PORT': cfg.get_port(),
    'CONN_MAX_AGE': _db_conn_max_age,
    'CONN_HEALTH_CHECKS': True,
}
if _default_engine == 'django.db.backends.postgresql':
    _pg_opts = cfg.build_postgres_connection_options()
    if _pg_opts:
        _default_db['OPTIONS'] = _pg_opts
DATABASES = {
    'default': _default_db,
    # Uncomment this portion if an xalt database exists
    'xalt': {
        #'ENGINE' : 'mysql.connector.django',
        'ENGINE': cfg.get_xalt_engine(),
        'NAME': cfg.get_xalt_name(),
        'USER': cfg.get_xalt_user(),
        'PASSWORD': cfg.get_xalt_password(),
        'HOST': cfg.get_xalt_host(),
        'CONN_MAX_AGE': _db_conn_max_age,
        'CONN_HEALTH_CHECKS': True,
    }
}

# Hosts/domain names that are valid for this site; required if DEBUG is False.
# ALLOWED_HOSTS env (comma-separated) overrides; else use [DEFAULT] server from hpcperfstats.ini.
# See https://docs.djangoproject.com/en/stable/ref/settings/#allowed-hosts
_ALLOWED = os.environ.get("ALLOWED_HOSTS", "").strip()
if _ALLOWED:
    ALLOWED_HOSTS = [h.strip() for h in _ALLOWED.split(",") if h.strip()]
else:
    _server = (cfg.get_server_name() or "").strip()
    if _server:
        ALLOWED_HOSTS = [h.strip() for h in _server.split(",") if h.strip()]
    else:
        ALLOWED_HOSTS = ["*"] if DEBUG else []

# Always allow the Django test host so RequestFactory and Django's test client
# work without DisallowedHost errors during tests.
if "testserver" not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ["testserver"]

# Allow Docker service hostname for internal health checks (e.g. supervisor_startup.sh curling http://web:8000)
if "*" not in ALLOWED_HOSTS and "web" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ["web"]

# Always allow loopback hosts for local development access through docker-compose
# port publishing (e.g. http://localhost:8000).
if "*" not in ALLOWED_HOSTS:
    for _loopback_host in ("localhost", "127.0.0.1"):
        if _loopback_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS = list(ALLOWED_HOSTS) + [_loopback_host]

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
# although not all choices may be available on all operating systems.
# In a Windows environment this must be set to your system time zone.
# Value comes from hpcperfstats.ini [DEFAULT] timezone.
TIME_ZONE = cfg.get_timezone()

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-us'

SITE_ID = 1

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale.

# If you set this to False, Django will not use timezone-aware datetimes.
USE_TZ = True

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
MEDIA_ROOT = os.path.join(DIR, 'media/')

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = '/media/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# Example: "/var/www/example.com/static/"
STATIC_ROOT = os.environ.get("STATIC_ROOT", "/home/hpcperfstats/staticfiles")

# URL prefix for static files.
# Example: "http://example.com/static/", "http://static.example.com/"
STATIC_URL = '/static/'

# Additional locations of static files.
# In some packaged/containerized installs this app-level static directory may
# not exist as a real filesystem path, so only include existing directories to
# avoid Django staticfiles.W004 warnings at startup.
_static_dir = os.path.join(DIR, "static")
STATICFILES_DIRS = (_static_dir,) if os.path.isdir(_static_dir) else ()

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Make this unique, and don't share it with anybody. Never commit a real key.
# In production set SECRET_KEY in the environment or in hpcperfstats.ini [DEFAULT] secret_key.
if not SECRET_KEY and DEBUG:
    warnings.warn("SECRET_KEY not set; using a dev-only default. Set SECRET_KEY in env for production.")
    SECRET_KEY = "dev-only-insecure-change-me"
elif not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in the environment for production.")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # insert your TEMPLATE_DIRS here
            #    'hpcperfstats_site/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Redis for ORM and view caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": cfg.get_redis_location(),
        "OPTIONS": {},
        "KEY_PREFIX": "hpcperfstats",
        "TIMEOUT": 300,
    }
}

# Suppress memcached key warnings emitted by Django key validation.
warnings.filterwarnings(
    "ignore",
    category=CacheKeyWarning,
    module=r"django\.core\.cache\.backends\.base",
)

# During test runs, avoid requiring a real Redis instance by switching to the
# in-memory cache backend. This keeps production configuration unchanged.
# Set HPCPERFSTATS_PYTEST_LIVE_REDIS=1 (e.g. tests/run_redis_cache_pytest_workflow.sh)
# to exercise Django's RedisCache against a real Redis on the compose network.
_use_live_redis_cache = os.environ.get(
    "HPCPERFSTATS_PYTEST_LIVE_REDIS", ""
).strip().lower() in ("1", "yes", "true")


def _running_under_pytest():
    """Detect pytest including ``python -m pytest`` (argv does not end with ``pytest``)."""
    if "pytest" in sys.argv:
        return True
    prog = os.path.basename(str(sys.argv[0] or ""))
    if prog == "pytest" or prog.startswith("pytest."):
        return True
    return "_pytest" in sys.modules


if _running_under_pytest() and not _use_live_redis_cache:
    CACHES["default"] = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "hpcperfstats-tests",
    }
# Full-page cache middleware removed in Django 4.0; ORM uses cache_utils.
MIDDLEWARE = (
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "hpcperfstats.site.hpcperfstats_site.middleware.DefaultSecurityHeadersMiddleware",
    "hpcperfstats.site.hpcperfstats_site.middleware.DefaultCacheControlMiddleware",
)

ROOT_URLCONF = 'hpcperfstats.site.hpcperfstats_site.urls'
# Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'hpcperfstats.site.hpcperfstats_site.wsgi'

# Django 6: DEFAULT_AUTO_FIELD defaults to BigAutoField; set explicitly for clarity.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INSTALLED_APPS = (
    "rest_framework",
    "corsheaders",
    "hpcperfstats.site.machine",
    "hpcperfstats.site.xalt",
    "hpcperfstats.site.hpcperfstats_site",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # Required for ArrayField and postgres ops (Django 6 system checks).
    "django.contrib.admin",
)
INTERNAL_IPS = ["127.0.0.1"]

# Django REST Framework: session auth for same-origin; allow credentials for SPA
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "hpcperfstats.site.machine.renderers.SafeJSONRenderer",
    ],
}
# CORS: allow same-origin by default; set CORS_ALLOWED_ORIGINS in production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SESSION_ENGINE = 'django.contrib.sessions.backends.file'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[DJANGO] %(levelname)s %(asctime)s %(module)s '
                      '%(name)s.%(funcName)s:%(lineno)s: %(message)s'
        },
        'agave': {
            'format': '[AGAVE] %(levelname)s %(asctime)s %(module)s '
                      '%(name)s.%(funcName)s:%(lineno)s: %(message)s'
        },
        'metrics': {
            'format':
                '[METRICS] %(levelname)s %(module)s %(name)s.%(funcName)s:%(lineno)s:'
                ' %(message)s user=%(user)s sessionId=%(sessionId)s op=%(operation)s'
                ' info=%(info)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
            'stream': sys.stdout,
        },
        'opbeat': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
        'metrics': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'metrics',
            'stream': sys.stdout,
        },
        'logfile': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
        # Swallow noisy DisallowedHost errors (e.g., bad 0.0.0.0 probes)
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'hpcperfstats_site': {
            'handlers': ['logfile',],
            'level': 'INFO',
        },
        'django': {
            'handlers': ['console', 'opbeat'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console', 'opbeat'],
            'level': 'DEBUG',
            'propagate': True
        },
        'opbeat': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'metrics': {
            'handlers': ['metrics'],
            'level': 'INFO',
        },
    },
}

# Only suppress DisallowedHost logging in non-DEBUG environments
if not DEBUG:
    LOGGING['loggers']['django.security.DisallowedHost'] = {
        'handlers': ['null'],
        'level': 'ERROR',
        'propagate': False,
    }
