#ifndef _CPU_COUNTER_METRICS_H_
#define _CPU_COUNTER_METRICS_H_

#define CPU_COUNTER_METRICS_KEYS \
  X(CPU_UTIL_TOTAL_ACCUM_US, "E,W=64", ""), \
  X(CPU_UTIL_USER_ACCUM_US, "E,W=64", ""), \
  X(CPU_UTIL_SYS_ACCUM_US, "E,W=64", ""), \
  X(CPU_UTIL_IRQ_ACCUM_US, "E,W=64", ""), \
  X(CPU_UTIL_NICE_ACCUM_US, "E,W=64", ""), \
  X(CPU_CLOCK_EST_CYCLES, "E,W=64", ""), \
  X(INSTR_RETIRED_ANY, "E,W=48", ""), \
  X(CPU_CLK_UNHALTED_CORE, "E,W=48", ""), \
  X(CPU_CLK_UNHALTED_REF, "E,W=48", ""), \
  X(MEM_LOAD_UOPS_RETIRED_L1_HIT, "E,W=48", ""), \
  X(MEM_LOAD_UOPS_RETIRED_L2_HIT, "E,W=48", ""), \
  X(MEM_LOAD_UOPS_RETIRED_LLC_HIT, "E,W=48", ""), \
  X(L1D_REPLACEMENT, "E,W=48", ""), \
  X(RETIRED_INSTRUCTIONS, "E,W=48", ""), \
  X(RETIRED_BRANCH_INSTR, "E,W=48", ""), \
  X(RETIRED_MISP_BRANCH_INSTR, "E,W=48", ""), \
  X(LS_DISPATCH, "E,W=48", ""), \
  X(FIXED_CTR0, "E,W=48", ""), \
  X(FIXED_CTR1, "E,W=48", ""), \
  X(FIXED_CTR2, "E,W=48", ""), \
  X(INST_RETIRED, "E,W=48", ""), \
  X(APERF, "E,W=48", ""), \
  X(MPERF, "E,W=48", ""), \
  X(EVENT_DRAM_CHANNEL_0, "E,W=48", ""), \
  X(EVENT_DRAM_CHANNEL_1, "E,W=48", ""), \
  X(EVENT_DRAM_CHANNEL_2, "E,W=48", ""), \
  X(EVENT_DRAM_CHANNEL_3, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_SCALAR_DOUBLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_128B_PACKED_DOUBLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_512B_PACKED_DOUBLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_SCALAR_SINGLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_128B_PACKED_SINGLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_256B_PACKED_SINGLE, "E,W=48", ""), \
  X(FP_ARITH_INST_RETIRED_512B_PACKED_SINGLE, "E,W=48", ""), \
  X(ARM_EST_FLOPS, "E,W=64,U=FLOP", ""), \
  X(ARM_DRAM_BW_BYTES, "E,W=64,U=B", ""), \
  X(DCGM_CPU_POWER_UTIL_W, "U=W", "Grace DCGM per-socket CPU power (W); same value on each core in that socket"), \
  X(DCGM_CPU_POWER_LIMIT_W, "U=W", "Grace DCGM per-socket CPU power limit (W); same value on each core in that socket")

#endif
