SUBDIRS = src tests

# Monitor-specific trees (not created by Autoconf); removed by distclean.
distclean-local:
	rm -rf .build-static

EXTRA_DIST = README README.md \
	third_party/nvidia-dcgm/README \
	third_party/nvidia-dcgm/dcgm_agent.h \
	third_party/nvidia-dcgm/dcgm_structs.h \
	third_party/nvidia-dcgm/dcgm_fields.h
