#!/usr/bin/env python3
"""Emit Docker Compose NUMA CPU pinning overlay from sysfs + hpcperfstats.ini.

Run on the **Linux deployment host** (not inside a container without sysfs).

Example:

  docker compose \\
    -f docker-compose.yaml \\
    -f docker-compose.numa-pinning.yaml \\
    up -d

See docs/DEPLOY_CONCURRENCY_AND_NUMA.md.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Repo root: .../HPCPerfStats/scripts -> parent
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
  sys.path.insert(0, str(_REPO_ROOT))

from hpcperfstats import conf_parser as cfg  # noqa: E402
from hpcperfstats.numa_topology import (  # noqa: E402
    SYSFS_NODE_ROOT,
    parse_sysfs_numa,
    select_node_pair,
    should_apply_numa_pinning,
)


def _build_overlay_yaml(
    web_cpuset: str,
    pipeline_cpuset: str,
    pin_proxy: bool,
) -> str:
  lines = [
      "# Generated by scripts/apply_compose_numa_pinning.py — do not edit by hand.",
      "services:",
      "  web:",
      f"    cpuset: \"{web_cpuset}\"",
      "  pipeline:",
      f"    cpuset: \"{pipeline_cpuset}\"",
  ]
  if pin_proxy:
    lines.extend(
        [
            "  proxy:",
            f"    cpuset: \"{web_cpuset}\"",
        ]
    )
  return "\n".join(lines) + "\n"


def _inactive_overlay_yaml() -> str:
  return (
      "# NUMA pinning inactive (single-node host, below threshold, or unsupported topology).\n"
      "# Empty overlay for `docker compose -f ... -f docker-compose.numa-pinning.yaml`.\n"
      "services: {}\n"
  )


def _parse_args() -> argparse.Namespace:
  p = argparse.ArgumentParser(description=__doc__)
  p.add_argument(
      "--output",
      "-o",
      type=Path,
      default=_REPO_ROOT / "docker-compose.numa-pinning.yaml",
      help="Write Compose overlay YAML here (default: repo root).",
  )
  p.add_argument(
      "--sysfs",
      type=Path,
      default=Path(SYSFS_NODE_ROOT),
  )
  p.add_argument("--dry-run", action="store_true", help="Print overlay to stdout only.")
  p.add_argument(
      "--check",
      action="store_true",
      help="Exit 0 if on-disk file matches computed overlay; else 1.",
  )
  return p.parse_args()


def main() -> int:
  args = _parse_args()
  sysfs_root = str(args.sysfs)
  nodes = parse_sysfs_numa(sysfs_root)
  eff = cfg.get_effective_cores()
  pin_min = cfg.get_cpuset_pin_min_total_cores()
  pin_per = cfg.get_cpuset_pin_min_cores_per_node()
  max_auto = cfg.get_numa_pin_max_nodes_auto()
  web_n = cfg.get_web_numa_node()
  pipe_n = cfg.get_pipeline_numa_node()

  apply_pin = should_apply_numa_pinning(
      effective_cores=eff,
      nodes=nodes,
      pin_min_total=pin_min,
      pin_min_per_node=pin_per,
      max_nodes_auto=max_auto,
      web_node=web_n,
      pipeline_node=pipe_n,
  )

  if apply_pin:
    pair = select_node_pair(nodes, web_node=web_n, pipeline_node=pipe_n)
    if pair is None:
      apply_pin = False
    else:
      wnode, pnode = pair
      content = _build_overlay_yaml(
          wnode.cpulist,
          pnode.cpulist,
          pin_proxy=cfg.get_pin_proxy_for_compose(),
      )

  if not apply_pin:
    content = _inactive_overlay_yaml()

  if args.dry_run:
    sys.stdout.write(content)
    return 0

  out = args.output
  if args.check:
    if not out.is_file():
      print(f"check: missing {out}", file=sys.stderr)
      return 1
    existing = out.read_text(encoding="utf-8")
    if existing != content:
      print("check: docker-compose.numa-pinning.yaml differs from computed overlay", file=sys.stderr)
      return 1
    return 0

  out.parent.mkdir(parents=True, exist_ok=True)
  out.write_text(content, encoding="utf-8")
  print(f"Wrote {out}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
