#!/usr/bin/env python3
"""Emit Docker Compose CPU pinning fragments (all services) from ini + host CPUs + sysfs NUMA.

Writes:

  - ``docker-compose.cpu-pinning.infra.yaml`` — ``db``, ``redis``, ``proxy``, ``rabbitmq``
  - ``docker-compose.cpu-pinning.app.yaml`` — ``web``, ``pipeline``

Run on the **Linux deployment host** (needs sysfs for NUMA overrides). Layout uses
``min(ini total_cores budget, os.cpu_count())`` and prioritizes **db** and **web**
(see ``hpcperfstats.dbload.lib.compose_cpu_layout``).

Examples:

  docker compose up -d

  # After regenerating fragments (optional unbound):
  python scripts/apply_compose_cpu_pinning.py --inactive

See docs/DEPLOY_CONCURRENCY_AND_NUMA.md.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
  sys.path.insert(0, str(_REPO_ROOT))

from hpcperfstats.dbload.lib import conf_parser as cfg  # noqa: E402
from hpcperfstats.dbload.lib.compose_cpu_layout import partition_responsive_cpusets  # noqa: E402
from hpcperfstats.dbload.lib.numa_topology import (  # noqa: E402
    SYSFS_NODE_ROOT,
    parse_sysfs_numa,
    select_node_pair,
    should_apply_numa_pinning,
)

_GEN = "scripts/apply_compose_cpu_pinning.py"


def _inactive_yaml() -> str:
  return (
      "# CPU pinning inactive (--inactive or use default committed empty fragments).\n"
      "services: {}\n"
  )


def _build_infra_yaml(cpus: dict) -> str:
  lines = [
      "# Generated by %s — do not edit by hand." % _GEN,
      "services:",
      "  db:",
      "    cpuset: \"%s\"" % cpus["db"],
      "  redis:",
      "    cpuset: \"%s\"" % cpus["redis"],
      "  proxy:",
      "    cpuset: \"%s\"" % cpus["proxy"],
      "  rabbitmq:",
      "    cpuset: \"%s\"" % cpus["rabbitmq"],
  ]
  return "\n".join(lines) + "\n"


def _build_app_yaml(cpus: dict) -> str:
  lines = [
      "# Generated by %s — do not edit by hand." % _GEN,
      "services:",
      "  web:",
      "    cpuset: \"%s\"" % cpus["web"],
      "  pipeline:",
      "    cpuset: \"%s\"" % cpus["pipeline"],
  ]
  return "\n".join(lines) + "\n"


def _parse_args() -> argparse.Namespace:
  p = argparse.ArgumentParser(description=__doc__)
  p.add_argument(
      "--infra-out",
      type=Path,
      default=_REPO_ROOT / "docker-compose.cpu-pinning.infra.yaml",
      help="Infra fragment path (db, redis, proxy, rabbitmq).",
  )
  p.add_argument(
      "--app-out",
      type=Path,
      default=_REPO_ROOT / "docker-compose.cpu-pinning.app.yaml",
      help="App fragment path (web, pipeline).",
  )
  p.add_argument(
      "--sysfs",
      type=Path,
      default=Path(SYSFS_NODE_ROOT),
      help="NUMA sysfs root (Linux only).",
  )
  p.add_argument(
      "--inactive",
      action="store_true",
      help="Write empty services:{} to both fragments (unbound / scheduler default).",
  )
  p.add_argument(
      "--dry-run",
      action="store_true",
      help="Print both YAML bodies to stdout (--- separator).",
  )
  p.add_argument(
      "--check",
      action="store_true",
      help="Exit 0 if both on-disk fragments match computed output; else 1.",
  )
  p.add_argument(
      "--total-cpus",
      type=int,
      default=None,
      metavar="N",
      help=(
          "Use N for the linear layout instead of min(ini total_cores, os.cpu_count()). "
          "Useful when cgroup-visible CPUs differ from the deployment budget."
      ),
  )
  return p.parse_args()


def main() -> int:
  args = _parse_args()
  if args.inactive:
    infra_body = app_body = _inactive_yaml()
  else:
    host = os.cpu_count() or 1
    if args.total_cpus is not None:
      if args.total_cpus < 1:
        print("--total-cpus must be >= 1", file=sys.stderr)
        return 1
      total = args.total_cpus
    else:
      total = min(cfg.get_effective_cores(), host)
    linear = partition_responsive_cpusets(total)
    cpus = dict(linear)
    nodes = parse_sysfs_numa(str(args.sysfs))
    pin_min = cfg.get_cpuset_pin_min_total_cores()
    pin_per = cfg.get_cpuset_pin_min_cores_per_node()
    max_auto = cfg.get_numa_pin_max_nodes_auto()
    web_n = cfg.get_web_numa_node()
    pipe_n = cfg.get_pipeline_numa_node()
    if should_apply_numa_pinning(
        effective_cores=cfg.get_effective_cores(),
        nodes=nodes,
        pin_min_total=pin_min,
        pin_min_per_node=pin_per,
        max_nodes_auto=max_auto,
        web_node=web_n,
        pipeline_node=pipe_n,
    ):
      pair = select_node_pair(nodes, web_node=web_n, pipeline_node=pipe_n)
      if pair is not None:
        wnode, pnode = pair
        # Single NUMA node: web and pipeline share the same full-socket cpulist.
        # Applying it would assign **all** host CPUs to web/pipeline and undo the
        # linear db/web/pipeline split — keep the linear layout instead.
        if wnode.node_id != pnode.node_id:
          cpus["web"] = wnode.cpulist
          cpus["pipeline"] = pnode.cpulist
          if cfg.get_pin_proxy_for_compose():
            cpus["proxy"] = wnode.cpulist
          else:
            cpus["proxy"] = linear["web"]
    infra_body = _build_infra_yaml(cpus)
    app_body = _build_app_yaml(cpus)

  if args.dry_run:
    sys.stdout.write(infra_body)
    sys.stdout.write("---\n")
    sys.stdout.write(app_body)
    return 0

  infra_path = args.infra_out
  app_path = args.app_out

  if args.check:
    for path, body in ((infra_path, infra_body), (app_path, app_body)):
      if not path.is_file():
        print("check: missing %s" % path, file=sys.stderr)
        return 1
      if path.read_text(encoding="utf-8") != body:
        print("check: %s differs from computed overlay" % path, file=sys.stderr)
        return 1
    return 0

  infra_path.parent.mkdir(parents=True, exist_ok=True)
  app_path.parent.mkdir(parents=True, exist_ok=True)
  infra_path.write_text(infra_body, encoding="utf-8")
  app_path.write_text(app_body, encoding="utf-8")
  print("Wrote %s and %s" % (infra_path, app_path))
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
