upstream django_server {
    server web:8000;
    keepalive 64;
}


server {
    listen 80;    
        
    client_max_body_size 14M;
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml
        application/rss+xml
        image/svg+xml;
    brotli on;
    brotli_comp_level 5;
    brotli_min_length 256;
    brotli_static off;
    brotli_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml
        application/rss+xml
        image/svg+xml;
    include /etc/nginx/nginx-static-files.conf;
}
    
