"""Emit syslog-ng fragment (``source s_net`` + allowlist filter) from ``hpcperfstats.ini``.

Run before ``syslog-ng`` starts in the pipeline container. Writes
``get_syslog_generated_config_path()`` (see ``[SYSLOG]`` in the ini).
"""
from __future__ import annotations

import os
import sys

from hpcperfstats import conf_parser as cfg


def render_syslog_ng_generated_text():
  """Return syslog-ng configuration snippet text."""
  nets = cfg.get_syslog_allow_from_ipv4_networks()
  use_tcp = cfg.get_syslog_listen_tcp()
  use_udp = cfg.get_syslog_listen_udp()
  if not use_tcp and not use_udp:
    raise RuntimeError(
        "SYSLOG listen_tcp and listen_udp cannot both be false.",
    )
  parts = []
  if use_tcp:
    parts.append(
        "tcp(ip(0.0.0.0) port(514) max-connections (100) log_iw_size(100000))",
    )
  if use_udp:
    parts.append("udp(ip(0.0.0.0) port(514))")
  inner = " ;\n       ".join(parts)
  if nets:
    mask_expr = " or\n       ".join("netmask(%s)" % n for n in nets)
  else:
    mask_expr = "netmask(0.0.0.0/0)"
  return (
      "# Generated by hpcperfstats.render_syslog_ng_generated - do not edit.\n"
      "source s_net {\n"
      "       %s;\n"
      "};\n"
      "\n"
      "filter f_hps_syslog_allow_net {\n"
      "       %s;\n"
      "};\n"
  ) % (inner, mask_expr)


def main(argv=None):
  argv = argv if argv is not None else sys.argv
  out_path = cfg.get_syslog_generated_config_path()
  os.makedirs(os.path.dirname(out_path), exist_ok=True)
  text = render_syslog_ng_generated_text()
  tmp = out_path + ".tmp"
  with open(tmp, "w", encoding="ascii") as f:
    f.write(text)
  os.replace(tmp, out_path)
  if "--print-path" in argv:
    print(out_path)
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
